# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Memory spills
#email: yi DOT ou AT gmx DOT de
description: >- # this means to ignore newlines until "baseurl:"
  Researcher and engineer. Loves simple design and clean code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "ouyi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: ouyi-cs
github_username: ouyi
author: Yi Ou

social_media:
  - { media_name: Github, fa_icon: fa-github-square, profile_link: "https://github.com/ouyi" }
  - { media_name: Linkedin, fa_icon: fa-linkedin-square, profile_link: "https://linkedin.com/in/ouyi-cs" }
  - { media_name: Xing, fa_icon: fa-xing-square, profile_link: "https://www.xing.com/profile/Yi_Ou3" }

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md

google_analytics: UA-37629863-6
